### ISSUE TITLE
add pre-commit hook for linting

### ISSUE THREAD

**Issue by stan-sack** [stan-sack/pinacolada#24]

**Comment by elliotjz** [comment]
Do you have a plan for how to do this? I just did some research and [this package](https://www.npmjs.com/package/husky) seems like it could do it.

**Comment by stan-sack** [comment]
Yeah that looks really good. We should lint and run the tests actually.

**Comment by stan-sack** [comment]
Yeah that looks really good. We should lint and run the tests actually.
