### ISSUE TITLE
Give stan admin access to repo to setup automated build and deploy to S3

### ISSUE THREAD

**Issue by stan-sack** [stan-sack/pinacolada#7]
I have a super rough frontend which fetches and displays images from an S3 bucket that I have setup until you can fix the permissions on mousaka-images. I would like to use Travis CI to do an automated build and deploy of the frontend but I think I need admin rights on the repo.

**Comment by laolsson** [comment]
I think a repository can only have one owner. Maybe the easiest is if I transfer ownership to you?

**Comment by stan-sack** [comment]
Do that Lars. I'll transfer back to you once the build is working 

_Sent from my Samsung SM-G900I using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by laolsson** [comment]
Just transfered to you

**Comment by stan-sack** [comment]
Are you sure lars? You are still marked as the owner.

**Comment by laolsson** [comment]
Have you accepted the transfer? I think you should have received a mail

**Comment by stan-sack** [comment]
Ah yeah it was in my junk emails. The link has expired though. Can you please send it again. Sorry.

**Comment by laolsson** [comment]
Check now

**Comment by stan-sack** [comment]
Yep it's mine now. Closing.
